// <auto-generated />
using System;
using GTKeeperAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GTKeeperAPI.Migrations
{
    [DbContext(typeof(GTKeeperContext))]
    partial class GTKeeperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GTKeeperAPI.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvisosSMS");

                    b.Property<string>("Imei");

                    b.Property<bool>("IsConfigPendingSync");

                    b.Property<bool>("IsProgramPendingSync");

                    b.Property<DateTime?>("LastCommitDate");

                    b.Property<DateTime?>("LastSync");

                    b.Property<DateTime>("LastUpdateConfig");

                    b.Property<DateTime>("LastUpdateProgram");

                    b.Property<bool>("MotorDiesel");

                    b.Property<string>("MovilAviso");

                    b.Property<string>("Nombre");

                    b.Property<int>("NumAbono");

                    b.Property<int>("NumPuertos");

                    b.Property<string>("PasswordSMS");

                    b.HasKey("ID");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GTKeeperAPI.Models.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeviceID");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Mensaje");

                    b.Property<DateTime>("Registrado");

                    b.Property<int>("Source");

                    b.Property<int>("Type");

                    b.HasKey("LogID");

                    b.HasIndex("DeviceID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GTKeeperAPI.Models.Programa", b =>
                {
                    b.Property<int>("ProgramaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeviceID");

                    b.Property<int>("Dias");

                    b.Property<TimeSpan>("Hora");

                    b.Property<int>("Sector");

                    b.Property<TimeSpan>("TiempoAbono");

                    b.Property<TimeSpan>("TiempoRiego");

                    b.HasKey("ProgramaID");

                    b.HasIndex("DeviceID");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("GTKeeperAPI.Models.Salida", b =>
                {
                    b.Property<int>("SalidaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Desde");

                    b.Property<int?>("DeviceID");

                    b.Property<DateTime?>("Hasta");

                    b.Property<int?>("Programa");

                    b.Property<int?>("Sector");

                    b.Property<int>("Tipo");

                    b.HasKey("SalidaID");

                    b.HasIndex("DeviceID");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("GTKeeperAPI.Models.Log", b =>
                {
                    b.HasOne("GTKeeperAPI.Models.Device", "Device")
                        .WithMany("Logs")
                        .HasForeignKey("DeviceID");
                });

            modelBuilder.Entity("GTKeeperAPI.Models.Programa", b =>
                {
                    b.HasOne("GTKeeperAPI.Models.Device", "Device")
                        .WithMany("Programas")
                        .HasForeignKey("DeviceID");
                });

            modelBuilder.Entity("GTKeeperAPI.Models.Salida", b =>
                {
                    b.HasOne("GTKeeperAPI.Models.Device", "Device")
                        .WithMany("Salidas")
                        .HasForeignKey("DeviceID");
                });
#pragma warning restore 612, 618
        }
    }
}
